spring:
  application:
    name: my-market-app

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:marketdb}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  sql:
    init:
      mode: never

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  thymeleaf:
    cache: false

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL:http://localhost:8082}/realms/market-realm

        registration:
          payment-client:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: payment-client
            client-name: payment-client
            client-secret: payment-client-secret
            scope:
              - payments

cache:
  ttl: PT1M

payment:
  service:
    url: ${PAYMENT_SERVICE_URL:http://localhost:8081/api/v1}

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

server:
  reactive:
    session:
      timeout: 30m

logging:
  level:
    ru.yandex.practicum: DEBUG
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO