version: '3.9'

services:

  db:
    image: postgres:16-alpine
    container_name: my-market-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: mymarketdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mymarketdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: my-market-app
    restart: unless-stopped

    depends_on:
      db:
        condition: service_healthy

    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: docker

      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/mymarketdb
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres

volumes:
  pgdata: