server:
  port: 8080

spring:
  application:
    name: my-market-app

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mymarket}
    username: ${SPRING_DATASOURCE_USERNAME:mymarket}
    password: ${SPRING_DATASOURCE_PASSWORD:mymarket}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  thymeleaf:
    cache: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace