server:
  port: 8080

spring:
  application:
    name: my-market-app

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/mymarket
    username: postgres
    password: postgres

  thymeleaf:
    cache: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always