services:

  market-db:
    image: postgres:16-alpine
    container_name: market-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: marketdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - market-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d marketdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped

    ports:
      - "6379:6379"

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.6.0
    command: start-dev --import-realm

    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_HEALTH_ENABLED: "true"
      PAYMENT_SERVICE_SECRET: payment-service-secret
      PAYMENT_CLIENT_SECRET: payment-client-secret

    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json

    ports:
      - "8082:8080"

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ready" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  payment-service:
    build:
      context: ..
      dockerfile: ../payment-service/Dockerfile

    container_name: payment-service
    restart: unless-stopped

    depends_on:
      market-db:
        condition: service_healthy
      keycloak:
        condition: service_healthy

    environment:
      DB_HOST: market-db
      DB_PORT: 5432
      DB_NAME: marketdb

      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

      KEYCLOAK_URL: http://keycloak:8080

    ports:
      - "8081:8081"

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

  market-app:
    build:
      context: ..
      dockerfile: ../market-app/Dockerfile

    container_name: market-app
    restart: unless-stopped

    depends_on:
      market-db:
        condition: service_healthy
      payment-service:
        condition: service_healthy
      redis:
        condition: service_started
      keycloak:
        condition: service_healthy

    environment:
      DB_HOST: market-db
      DB_PORT: 5432
      DB_NAME: marketdb

      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

      REDIS_HOST: redis
      REDIS_PORT: 6379

      PAYMENT_SERVICE_URL: http://payment-service:8081/api/v1

      KEYCLOAK_URL: http://keycloak:8080

    ports:
      - "8080:8080"

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

  gw:
    image: nginx:1.29.0-alpine-perl
    container_name: gw
    restart: unless-stopped

    depends_on:
      market-app:
        condition: service_started

    ports:
      - "80:80"

    volumes:
      - ./proxy/nginx-market-proxy.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  market-data: